// AUTO-GENERATED FROM .env - DO NOT EDIT MANUALLY OR COMMIT TO GIT
#ifndef BLINKY_CONFIG_H
#define BLINKY_CONFIG_H

#define WIFI_SSID "Sahil Gupta"
#define WIFI_PASSWORD "8360054278@aa"

#endif // BLINKY_CONFIG_H
